CREATE PROCEDURE FI_SP_ConsBeneficiario
    @ID BIGINT
AS
BEGIN
    IF @ID = 0
        SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS
    ELSE
        SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WHERE ID = @ID
END
