CREATE PROCEDURE FI_SP_VerificaBeneficiario
    @CPF       VARCHAR(14),
    @IDCLIENTE BIGINT = NULL -- Permite uso tanto com quanto sem ID do cliente
AS
BEGIN
    IF @IDCLIENTE IS NULL
        SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF
    ELSE
        SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE
END
