CREATE DATABASE FI_Entrevista;
GO

USE FI_Entrevista;
GO

CREATE TABLE Cliente (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DataNascimento DATETIME NOT NULL
);
GO

CREATE TABLE Beneficiario (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdCliente INT NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CONSTRAINT FK_Beneficiario_Cliente FOREIGN KEY (IdCliente) REFERENCES Cliente(Id),
    CONSTRAINT UQ_Beneficiario_CPF_Cliente UNIQUE (IdCliente, CPF)
);
GO